### ISSUE TITLE
Boot Loop

### ISSUE THREAD

**Issue by TheEugeneKam** [jsassu20/ThinkPad-T450-Mojave#1]
The current files send my laptop on a boot loop after updating. Everything
was set up correctly and worked fairly well. I tried reinstalling the OS as well as, still same results. 
The only difference between our machines is that I have i5-5300U. I attached the files that had a successful boot for me here. including tack pad working okay and battery percentage working. The only real issue was that headphone jack didn't work and the SD card. 
I think this build was from april 
https://drive.google.com/drive/folders/1O833wZXbLm01T4D6snUkXNWm9FAsDfV8?usp=sharing

**Comment by jsassu20** [comment]
Issue should be resolved now, grab the new release and swap out the files. Everything should work fine now. Make sure you run the kext install script in the kexts folder to install all kexts in System folder to /Library/Extensions. It will automatically repair the permissions as well so you don't need to worry about that.

**Comment by jsassu20** [comment]
TouchPad and SD Card reader should be fixed as well

**Comment by TheEugeneKam** [comment]
Thanks for the quick reply! 
The boot loop issue seems to have been resolved. After deleting all the old files and clearing the recycling bin pasted all the new files into the appropriate place in EFI partition. Ran install kext script in the kext folder and no luck on the full boot.
At the black loading screen with apple logo, where it would reboot before, the loading bar gets to about half way and slows down, it fills in about 2 minutes and just kinda hangs. No reboots or anything. 
Attached is a EFI/Clover folder that looks good to me, ran the script there. 
When i boot in verbose mode it gets to this point screenshot) and sits there..(attached in the 
![IMG_0751](https://user-images.githubusercontent.com/27051915/57659340-05973400-75b0-11e9-9743-2a85e67f543c.jpg)
![IMG_0750](https://user-images.githubusercontent.com/27051915/57659341-062fca80-75b0-11e9-941a-797b30906182.jpg)

**Comment by jsassu20** [comment]
Ok I just updated everything again about 3 minutes ago. Try out the new setup and if the first config doesn't work try the config_alt.plist by going into options at the clover screen and selecting the config option.

**Comment by TheEugeneKam** [comment]
Same thing as other tickets, now it does the same thing that was happening initially and reboots about half way through the loading. Would it be possible to combine kexts and the plush and stuff from the attachment above. That the only one that I can still use to boot OS

**Comment by jsassu20** [comment]
The issue is a framebuffer malfunction related to the presence of the IMEI device or the configured memory in your BIOS for the video display for DMVT. My BIOS is modified so I can change mine at will, other systems are unfortunately fixed at a specific amount of memory based on a few different factors. I think its most likely that yours was set to 32MB and the IGPU configuration I was using was causing the kernel panic because my configuration utilizes 128MB DVMT. Ive updated the release with the 32MB DVMT IGPU configuration settings in ACPI/Devices/Properties/PciRoot(0x0)/Pci(0x2,0x0).... See if this doesn't take care of your issue. I'm going to create a few different config.plists for different circumstances and label them for easy use. Give me about 30 minutes and I'll post the new build.

**Comment by TheEugeneKam** [comment]
Can confirm that stock config plist fixed the boot issue in the new build on a non unlocked T450 with touchpad replacement! Thank you!

**Comment by TheEugeneKam** [comment]
Had a quick question for you though, Should I use another plist or kext setup if I am using t440 trackpad like you are? I installed mine a few weeks back and it goes seem to work better with mac os!

**Comment by jsassu20** [comment]
you can If you want I'll add it right now it'll be in the utilities folder

**Comment by TheEugeneKam** [comment]
Ooo that would be awesome. Short tutorial on what to swap would also be great!

**Comment by jsassu20** [comment]
I added a .command file that will do everything for you. Just run the file and make sure you EFI partition with CLOVER is mounted but it should already be if you swap the files out the way you normally do. It's all set bro. Everything you need is there and the instructions as well.

**Comment by TheEugeneKam** [comment]
Awesome, this driver works a million times better! As a quick note, the path for the script to instal lthe drivers is wrong in the guide. Guide says that the script is located in xxx/kexts/ but its in xxx/utilities/xx :D

**Comment by TheEugeneKam** [comment]
Just did notice that after the trackpad update, the brightness controls don't work anymore lol

**Comment by jsassu20** [comment]
try fn + f5 and f6

**Comment by jsassu20** [comment]
did you run the script?

**Comment by TheEugeneKam** [comment]
Tried that and I did. All ran successfully. Volume controls still work but screen brightness is dead.

**Comment by jsassu20** [comment]
Does your ACPI/patched folder show SSDT-ASTP.aml? that's what's responsible for brightness

**Comment by jsassu20** [comment]
if it still shows SSDT-VPS2.aml that needs to go

**Comment by jsassu20** [comment]
also updated the t440 folder with my config.plist try that as well I added the 32 mb dvmd to it

**Comment by TheEugeneKam** [comment]
My folder does have the SSDT-VPS2.aml, that is what is included in the last release for the t450 public.

**Comment by TheEugeneKam** [comment]
ah i see it in the trackpad folder. the script didnt seem to have copied that over. I will manually swap the vps2 for the astp file.
