### ISSUE TITLE
IOConsoleUsers: gIOScreenLockSatate

### ISSUE THREAD

**Issue by MauricioAlv** [jsassu20/ThinkPad-T450-Mojave#2]
Hello,

I'm trying to use this configuration on my T450 Device, but I get the following:

IOConsoleUsers: gIOScreenLockSatate 3,

Do you have any idea what it might be? I thank you very much for your help.

**Comment by jsassu20** [comment]
Ok I just updated everything again about 3 minutes ago. Try out the new setup and if the first config doesn't work try the config_alt.plist by going into options at the clover screen and selecting the config option.
